[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#222222"
idle_fg = "#93a1a1"

[icons]
name = "none"


[[block]]
block = "net"
device = "wlan0"
ip = true
speed_up = false
graph_up = false
speed_down = false
graph_down = false
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
